# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.TextField(verbose_name='Nome')),
                ('email', models.TextField(verbose_name='Email')),
                ('username', models.TextField(verbose_name='Usuário')),
                ('password', models.TextField(verbose_name='Senha')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'ordering': ['-nome'],
            },
        ),
    ]
