# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastro',
            name='email',
            field=models.CharField(max_length=300, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='nome',
            field=models.CharField(max_length=300, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='password',
            field=models.CharField(max_length=300, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='username',
            field=models.CharField(max_length=300, verbose_name='Usuário'),
        ),
    ]
