# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-29 14:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0002_auto_20171029_1217'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cadastro',
        ),
    ]
